<nav id="mobile-nav">
<div class="logo-mobile" role="banner"><a href="/germany/"><img src="/images/HHC_logo_2pms.png" width="175" height ="65" alt="Bayada logo - returns to home page"></a></div>
  <ul id="menu">
        <li><a href="index.asp">&#252;ber BAYADA</a></li>
        <li><a href="philosophie.asp">Die Philosophie</a></li>
        <li><a href="werte.asp">Unsere Werte</a></li>
        <li><a href="stellenangebote.asp">Stellenangebote</a></li>
        <li><a href="kontakt.asp">Kontakt</a></li>
       <!--  <li><a href="/app/find-an-office/">Find an Office</a></li>
        <li><a href="/services.asp">Our Services</a>
             <ul>
                <li><a href="/services.asp">Our Services</a></li>
                <li><a href="/our-care-professionals.asp">Our Care Professionals</a></li>
                <li><a href="/why-home-health-care.asp">Why Home Health Care?</a></li>
                <li><a href="/homehealthcare/"><span class='uppercase'>Bayada</span> Home Health Care</a></li>
                <li><a href="/pediatrics"><span class='uppercase'>Bayada</span> Pediatrics</a></li>
                <li><a href="/hospice/"><span class='uppercase'>Bayada</span> Hospice</a></li>
                <li><a href="/services-habilitation.asp"><span class='uppercase'>Bayada</span> Habilitation</a></li>
                <li><a href='/services-staffing.asp'><span class='uppercase'>Bayada</span> Staffing</a></li>
                <li><a href='/physicianservices/'>Physician Services</a></li>
                <li><a href="/medmanagement/">Medication Management</a></li>
            </ul>
        </li>
        <li><a href="https://jobs.bayada.com/">Careers in Caring</a></li>
        <li><a href="/about.asp">About BAYADA</a>
            <ul>
                <li><a href="/about.asp">About Us</a></li>
                <li><a href="/about-mark-baiada.asp">Message from Mark Baiada</a></li>
                <li><a href="bayada-way-history.asp">History of BAYADA</a></li>
                <li><a href="/accreditation.asp">Accreditation</a></li>
                <li><a href="/compliance/">Compliance and Privacy</a></li>
                <li><a href="/advocacy.asp">Advocacy</a></li>
                <li><a href="/app/find-an-office/">Find an Office</a></li>
                <li><a href="/technology.asp">Technology</a></li>
                <li><a href="https://donatenow.networkforgood.org/1441751">BAYADA Foundation</a></li>
            </ul>
        </li>
        <li><a href="/the-bayada-way.asp">The Bayada Way</a>
             <ul>
                <li><a href="/the-bayada-way.asp">The BAYADA WAY</a></li>
                <li><a href="/a-letter-from-mark.asp">A Letter from Mark</a></li>
                <li><a href="/bayada-way-articles.asp">Published Articles</a></li>
                <li><a href="/testimonials.asp">Testimonials</a></li>
                <li><a href="/client-reviews.asp">Client Reviews</a></li>
                <li><a href="/diversity.asp">Diversity</a></li>
                <li><a href="/legacy/">Lasting Legacy Plan</a></li>
            </ul>
        </li>
        <li><a href="/contact.asp">Contact Us</a></li> -->
        <li><a class='emp-login-mobile' href="/employee-login.asp">Employee Login</a></li>
        <li class="nav-search">
            <form action="/search.asp" method="get" role="search">
                <label for="search-nav" class="hidden">search</label>
                <input id="search-nav" type="text" role="textbox" value="Search this Site" onblur="if(this.value=='') this.value='Search this Site';" onfocus="if(this.value=='Search this Site') this.value='';" name="search">
                <input type="submit" class="input_submit" value="submit">
            </form>
        </li>
    <li class="social">
        <a href="/"><img src="/images/social/home.png" height="30" width="30" alt="return to BAYADA home"></a><a href="https://www.facebook.com/BAYADAHomeHealthCare"><img src="/images/social/facebook.png" height="30" width="30" alt="facebook"></a><a href="https://www.linkedin.com/company/19472"><img src="/images/social/linkedin.png" height="30" width="30" alt="linkedin"></a><a href="https://www.youtube.com/user/bayadanurses"><img src="/images/social/youtube.png" height="30" width="30" alt="youtube"></a><a href="https://twitter.com/BayadaHHC"><img src="/images/social/twitter.png" height="30" width="30" alt="twitter"></a>
    </li>
</ul>
</nav>
<!-- end mobile navigation -->
<div class='head-width'>
    <div class='desk-nav'>
        <div class='nav-span-new fixed-nav cp-nav'>
            <nav class="nav">
              <ul class='flexnav nav-width nav-padding'>
                  <li class="left-logo" role="banner">
                      <a href="/germany/"><img src="/images/HHC_logo_2pms.png" width="175" height ="65" alt="Bayada logo"></a>
                  </li>
                  <li><a href="philosophie.asp">Die Philosophie</a></li>
                  <li><a href="werte.asp">Unsere Werte</a></li>
                  <li><a href="stellenangebote.asp">Stellenangebote</a></li>
                  <li><a href="kontakt.asp">Kontakt</a></li>
             </ul>
        </nav>
    </div><!-- end flexnav -->
  </div><!-- end nav-span -->
</div>
